"""Add shipping method to order

Revision ID: 19e440e5566e
Revises: 9d685357fb49
Create Date: 2026-06-30 16:40:04.706159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e440e5566e'
down_revision: Union[str, Sequence[str], None] = '9d685357fb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('shipping_method', sa.Enum('standard', 'express', name='shippingmethod'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'shipping_method')
    # ### end Alembic commands ###
