"""Initial schema

Revision ID: 3118f1537aa6
Revises: 
Create Date: 2026-06-28 08:40:29.854148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3118f1537aa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Brand',
    sa.Column('brand_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('brand_code', sa.String(length=50), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'hidden'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_Brand_brand_code'), 'Brand', ['brand_code'], unique=True)
    op.create_table('Category',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'hidden'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Category.category_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_Category_category_code'), 'Category', ['category_code'], unique=True)
    op.create_table('Customer',
    sa.Column('customer_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other'), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('default_address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'locked'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_Customer_email'), 'Customer', ['email'], unique=True)
    op.create_index(op.f('ix_Customer_phone'), 'Customer', ['phone'], unique=True)
    op.create_table('User',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('admin', 'staff'), server_default='staff', nullable=False),
    sa.Column('status', sa.Enum('active', 'locked'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('Voucher',
    sa.Column('voucher_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('voucher_code', sa.String(length=50), nullable=False),
    sa.Column('voucher_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Enum('percent', 'fixed'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=15, scale=0), server_default='0', nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('active', 'hidden', 'expired'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('voucher_id')
    )
    op.create_index(op.f('ix_Voucher_voucher_code'), 'Voucher', ['voucher_code'], unique=True)
    op.create_table('AuditLog',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_AuditLog_user_id'), 'AuditLog', ['user_id'], unique=False)
    op.create_table('Cart',
    sa.Column('cart_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'checked_out', 'abandoned'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.customer_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_index(op.f('ix_Cart_customer_id'), 'Cart', ['customer_id'], unique=False)
    op.create_index(op.f('ix_Cart_session_id'), 'Cart', ['session_id'], unique=False)
    op.create_table('Order',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('receiver_name', sa.String(length=150), nullable=False),
    sa.Column('receiver_phone', sa.String(length=20), nullable=False),
    sa.Column('shipping_address', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.Enum('cod', 'bank_transfer', 'online'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'refunded'), server_default='pending', nullable=False),
    sa.Column('voucher_id', sa.BigInteger(), nullable=True),
    sa.Column('voucher_code_snapshot', sa.String(length=50), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('voucher_discount_amount', sa.Numeric(precision=15, scale=0), server_default='0', nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=15, scale=0), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('order_status', sa.Enum('pending', 'confirmed', 'preparing', 'shipping', 'completed', 'cancelled'), server_default='pending', nullable=False),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.customer_id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['Voucher.voucher_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_Order_order_code'), 'Order', ['order_code'], unique=True)
    op.create_index(op.f('ix_Order_order_status'), 'Order', ['order_status'], unique=False)
    op.create_table('Product',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gender_target', sa.Enum('men', 'women', 'unisex', 'kids'), nullable=True),
    sa.Column('status', sa.Enum('active', 'hidden', 'discontinued'), server_default='active', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['Brand.brand_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['Category.category_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_Product_product_code'), 'Product', ['product_code'], unique=True)
    op.create_table('OrderStatusLog',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_OrderStatusLog_order_id'), 'OrderStatusLog', ['order_id'], unique=False)
    op.create_table('ProductColor',
    sa.Column('color_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('color_code', sa.String(length=50), nullable=False),
    sa.Column('color_name', sa.String(length=100), nullable=False),
    sa.Column('hex_code', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('discount_type', sa.Enum('none', 'percent', 'fixed'), server_default='none', nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('active', 'hidden', 'discontinued'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Product.product_id'], ),
    sa.PrimaryKeyConstraint('color_id')
    )
    op.create_index(op.f('ix_ProductColor_product_id'), 'ProductColor', ['product_id'], unique=False)
    op.create_table('ReturnRequest',
    sa.Column('return_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'completed'), server_default='pending', nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('processed_by', sa.BigInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('return_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_ReturnRequest_customer_id'), 'ReturnRequest', ['customer_id'], unique=False)
    op.create_table('VoucherUsage',
    sa.Column('usage_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('voucher_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customer.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['Voucher.voucher_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index(op.f('ix_VoucherUsage_customer_id'), 'VoucherUsage', ['customer_id'], unique=False)
    op.create_index(op.f('ix_VoucherUsage_order_id'), 'VoucherUsage', ['order_id'], unique=False)
    op.create_index(op.f('ix_VoucherUsage_voucher_id'), 'VoucherUsage', ['voucher_id'], unique=False)
    op.create_table('ProductImage',
    sa.Column('image_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('color_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['ProductColor.color_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_ProductImage_color_id'), 'ProductImage', ['color_id'], unique=False)
    op.create_table('ProductSku',
    sa.Column('sku_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('color_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'out_of_stock', 'discontinued'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['ProductColor.color_id'], ),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_index(op.f('ix_ProductSku_color_id'), 'ProductSku', ['color_id'], unique=False)
    op.create_index(op.f('ix_ProductSku_sku_code'), 'ProductSku', ['sku_code'], unique=True)
    op.create_table('CartItem',
    sa.Column('cart_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['Cart.cart_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['ProductSku.sku_id'], ),
    sa.PrimaryKeyConstraint('cart_item_id')
    )
    op.create_index(op.f('ix_CartItem_cart_id'), 'CartItem', ['cart_id'], unique=False)
    op.create_table('OrderDetail',
    sa.Column('order_detail_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_code_snapshot', sa.String(length=50), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('color_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('size_snapshot', sa.String(length=20), nullable=False),
    sa.Column('image_url_snapshot', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('discount_type_snapshot', sa.String(length=20), nullable=False),
    sa.Column('discount_value_snapshot', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discounted_price', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['Order.order_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['ProductSku.sku_id'], ),
    sa.PrimaryKeyConstraint('order_detail_id')
    )
    op.create_index(op.f('ix_OrderDetail_order_id'), 'OrderDetail', ['order_id'], unique=False)
    op.create_table('StockLog',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('change_quantity', sa.Integer(), nullable=False),
    sa.Column('stock_before', sa.Integer(), nullable=False),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('reason_note', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['ProductSku.sku_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_StockLog_sku_id'), 'StockLog', ['sku_id'], unique=False)
    op.create_table('ReturnItem',
    sa.Column('return_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.BigInteger(), nullable=False),
    sa.Column('order_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('intact', 'defective', 'wrong_item'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_detail_id'], ['OrderDetail.order_detail_id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['ReturnRequest.return_id'], ),
    sa.PrimaryKeyConstraint('return_item_id')
    )
    op.create_index(op.f('ix_ReturnItem_return_id'), 'ReturnItem', ['return_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ReturnItem_return_id'), table_name='ReturnItem')
    op.drop_table('ReturnItem')
    op.drop_index(op.f('ix_StockLog_sku_id'), table_name='StockLog')
    op.drop_table('StockLog')
    op.drop_index(op.f('ix_OrderDetail_order_id'), table_name='OrderDetail')
    op.drop_table('OrderDetail')
    op.drop_index(op.f('ix_CartItem_cart_id'), table_name='CartItem')
    op.drop_table('CartItem')
    op.drop_index(op.f('ix_ProductSku_sku_code'), table_name='ProductSku')
    op.drop_index(op.f('ix_ProductSku_color_id'), table_name='ProductSku')
    op.drop_table('ProductSku')
    op.drop_index(op.f('ix_ProductImage_color_id'), table_name='ProductImage')
    op.drop_table('ProductImage')
    op.drop_index(op.f('ix_VoucherUsage_voucher_id'), table_name='VoucherUsage')
    op.drop_index(op.f('ix_VoucherUsage_order_id'), table_name='VoucherUsage')
    op.drop_index(op.f('ix_VoucherUsage_customer_id'), table_name='VoucherUsage')
    op.drop_table('VoucherUsage')
    op.drop_index(op.f('ix_ReturnRequest_customer_id'), table_name='ReturnRequest')
    op.drop_table('ReturnRequest')
    op.drop_index(op.f('ix_ProductColor_product_id'), table_name='ProductColor')
    op.drop_table('ProductColor')
    op.drop_index(op.f('ix_OrderStatusLog_order_id'), table_name='OrderStatusLog')
    op.drop_table('OrderStatusLog')
    op.drop_index(op.f('ix_Product_product_code'), table_name='Product')
    op.drop_table('Product')
    op.drop_index(op.f('ix_Order_order_status'), table_name='Order')
    op.drop_index(op.f('ix_Order_order_code'), table_name='Order')
    op.drop_table('Order')
    op.drop_index(op.f('ix_Cart_session_id'), table_name='Cart')
    op.drop_index(op.f('ix_Cart_customer_id'), table_name='Cart')
    op.drop_table('Cart')
    op.drop_index(op.f('ix_AuditLog_user_id'), table_name='AuditLog')
    op.drop_table('AuditLog')
    op.drop_index(op.f('ix_Voucher_voucher_code'), table_name='Voucher')
    op.drop_table('Voucher')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Customer_phone'), table_name='Customer')
    op.drop_index(op.f('ix_Customer_email'), table_name='Customer')
    op.drop_table('Customer')
    op.drop_index(op.f('ix_Category_category_code'), table_name='Category')
    op.drop_table('Category')
    op.drop_index(op.f('ix_Brand_brand_code'), table_name='Brand')
    op.drop_table('Brand')
    # ### end Alembic commands ###
