"""add applied_voucher_code to Cart

Revision ID: 68b00dd935bc
Revises: 19e440e5566e
Create Date: 2026-06-30 22:10:45.745301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b00dd935bc'
down_revision: Union[str, Sequence[str], None] = '19e440e5566e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cart', sa.Column('applied_voucher_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cart', 'applied_voucher_code')
    # ### end Alembic commands ###
