"""Add User cart relationship

Revision ID: 7a9bd1446edb
Revises: fecd0849e7ce
Create Date: 2026-06-29 20:52:40.014498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9bd1446edb'
down_revision: Union[str, Sequence[str], None] = 'fecd0849e7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cart', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_Cart_user_id'), 'Cart', ['user_id'], unique=False)
    op.create_foreign_key(None, 'Cart', 'User', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Cart', type_='foreignkey')
    op.drop_index(op.f('ix_Cart_user_id'), table_name='Cart')
    op.drop_column('Cart', 'user_id')
    # ### end Alembic commands ###
