"""Add max_usage_per_customer to Voucher

Revision ID: 9d685357fb49
Revises: 9430dcff9534
Create Date: 2026-06-30 10:38:49.335540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d685357fb49'
down_revision: Union[str, Sequence[str], None] = '9430dcff9534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Voucher', sa.Column('max_usage_per_customer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Voucher', 'max_usage_per_customer')
    # ### end Alembic commands ###
