"""add_is_active_to_cart_item

Revision ID: fecd0849e7ce
Revises: 3118f1537aa6
Create Date: 2026-06-28 18:15:01.286029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecd0849e7ce'
down_revision: Union[str, Sequence[str], None] = '3118f1537aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CartItem', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CartItem', 'is_active')
    # ### end Alembic commands ###
